### PR TITLE
Build with LTO and Ofast

### PR DESCRIPTION
**Pull request by edisionnano**
This enhances performance in our Yuzu EA builds. 
For example on Link's awakening:
Without:
image
With:
image

These optimizations have the potential to break some stuff so some testing is needed.

### CODE REVIEW

**Review by agent255 — COMMENTED** [review]
Change the -Ofast to -O2 because it'll be a lot more stable. -Ofast Disregards strict standards compliance. -Ofast enables all -O3 optimizations. It also enables optimizations that are not valid for all standard-compliant programs.  Also try to enable PGO.

**Comment by edisionnano** [comment]
> Change the -Ofast to -O2 because it'll be a lot more stable. -Ofast Disregards strict standards compliance. -Ofast enables all -O3 optimizations. It also enables optimizations that are not valid for all standard-compliant programs. Also try to enable PGO.

I'm well aware of what ofast does, that's why I mentioned testing is needed. It is O3+fast math. I don't want to do O2 that's the default. Why would I enable pgo? What profiling data would I use for it?

**Comment by MGThePro** [comment]
> that's why I mentioned testing is needed.

testing only gets you so far when there's thousands of different games to test for unpredictable behavior caused by ofast. And yuzu ~~spaghetti~~ source code might not handle o3 well either.
LTO seems to be safe, but gcc documentation states that with it enabled, all linked files should be compiled with the same options, not sure if that is the case here.

**Comment by Tachi107** [comment]
> Change the -Ofast to -O2 because it'll be a lot more stable

CMake's `Release` build type already passes `-O3` to the compiler...

**Pull request closed without merging**
